import { PlanDefinition, SubscriptionPlanId } from '@/types/subscription';

export const TRIAL_DURATION_DAYS = 30;

export const LAUNCH_OFFER_CONFIG = {
  enabled: true,
  discountedMonthlyPrice: 199, // ₹199/mo for first 3 months
  discountMonths: 3,
  freeMigration: true,
  freeSetupCall: true,
  priceLockMonths: 12,
  maxEligibleProperties: 100,
};

export const PLANS: Record<SubscriptionPlanId, PlanDefinition> = {
  FREE: {
    id: 'FREE',
    name: 'Free',
    monthlyPrice: 0,
    yearlyPrice: 0,
    suitableFor: 'Trial users and very small properties',
    features: [
      '1 Property',
      '5 Rooms limit',
      'Up to 20 check-ins / month',
      'Basic guest records',
      'QR guest self check-in',
      'Basic occupancy view',
      'Offline data entry',
      'Up to 5 PDF/CSV exports / month',
    ],
    entitlements: {
      maxProperties: 1,
      maxRoomsPerProperty: 5,
      monthlyCheckInLimit: 20,
      unlimitedCheckIns: false,
      qrCheckIn: true,
      offlineMode: true,
      basicReports: true,
      advancedReports: false,
      pdfExport: true,
      csvExport: true,
      unlimitedExports: false,
      ocrScanning: false,
      staffAccounts: false,
      backups: false,
      restore: false,
      multiProperty: false,
      centralizedDashboard: false,
      rolePermissions: false,
      apiAccess: false,
      prioritySupport: false,
    },
  },
  STARTER: {
    id: 'STARTER',
    name: 'Starter',
    monthlyPrice: 299,
    yearlyPrice: 2999, // ~2 months free
    suitableFor: 'Small homestays and guesthouses',
    features: [
      '1 Property',
      'Up to 5 Rooms',
      'Unlimited guest check-ins',
      'Offline mode',
      'Unlimited basic PDF & CSV exports',
      'QR guest self check-in',
      'Guest history search',
    ],
    entitlements: {
      maxProperties: 1,
      maxRoomsPerProperty: 5,
      monthlyCheckInLimit: 'unlimited',
      unlimitedCheckIns: true,
      qrCheckIn: true,
      offlineMode: true,
      basicReports: true,
      advancedReports: false,
      pdfExport: true,
      csvExport: true,
      unlimitedExports: true,
      ocrScanning: false,
      staffAccounts: false,
      backups: false,
      restore: false,
      multiProperty: false,
      centralizedDashboard: false,
      rolePermissions: false,
      apiAccess: false,
      prioritySupport: false,
    },
  },
  PROFESSIONAL: {
    id: 'PROFESSIONAL',
    name: 'Professional',
    monthlyPrice: 799,
    yearlyPrice: 7999, // ~2 months free
    popular: true,
    suitableFor: 'Hotels, resorts & busy homestays',
    features: [
      '1 Property',
      'Up to 30 Rooms',
      'Unlimited check-ins',
      'Camera OCR ID Scanning (Aadhaar, PAN, DL, Passport)',
      'Up to 5 Staff accounts with permissions',
      'Advanced occupancy & revenue reports',
      'Automated local & cloud backups',
      'Priority customer support',
    ],
    entitlements: {
      maxProperties: 1,
      maxRoomsPerProperty: 30,
      monthlyCheckInLimit: 'unlimited',
      unlimitedCheckIns: true,
      qrCheckIn: true,
      offlineMode: true,
      basicReports: true,
      advancedReports: true,
      pdfExport: true,
      csvExport: true,
      unlimitedExports: true,
      ocrScanning: true,
      staffAccounts: true,
      backups: true,
      restore: true,
      multiProperty: false,
      centralizedDashboard: false,
      rolePermissions: true,
      apiAccess: false,
      prioritySupport: true,
    },
  },
  MULTI_PROPERTY: {
    id: 'MULTI_PROPERTY',
    name: 'Multi-Property',
    monthlyPrice: 1999,
    yearlyPrice: 19999, // ~2 months free
    suitableFor: 'Property managers & multi-location hosts',
    features: [
      'Up to 10 Properties',
      'Unlimited Rooms',
      'Unlimited check-ins & OCR scans',
      'Centralized multi-property dashboard',
      'Role-based staff permissions',
      'Consolidated multi-property reports',
      'Automated backups & restore',
      'Dedicated support',
    ],
    entitlements: {
      maxProperties: 10,
      maxRoomsPerProperty: 999,
      monthlyCheckInLimit: 'unlimited',
      unlimitedCheckIns: true,
      qrCheckIn: true,
      offlineMode: true,
      basicReports: true,
      advancedReports: true,
      pdfExport: true,
      csvExport: true,
      unlimitedExports: true,
      ocrScanning: true,
      staffAccounts: true,
      backups: true,
      restore: true,
      multiProperty: true,
      centralizedDashboard: true,
      rolePermissions: true,
      apiAccess: false,
      prioritySupport: true,
    },
  },
  ENTERPRISE: {
    id: 'ENTERPRISE',
    name: 'Enterprise',
    monthlyPrice: 0,
    yearlyPrice: 0,
    suitableFor: 'Hotel groups and chains (Custom Quote)',
    features: [
      'Unlimited properties & rooms',
      'Custom API & PMS integrations',
      'Onboarding & staff training',
      'SLA support & dedicated manager',
      'Custom security reviews',
    ],
    entitlements: {
      maxProperties: 9999,
      maxRoomsPerProperty: 9999,
      monthlyCheckInLimit: 'unlimited',
      unlimitedCheckIns: true,
      qrCheckIn: true,
      offlineMode: true,
      basicReports: true,
      advancedReports: true,
      pdfExport: true,
      csvExport: true,
      unlimitedExports: true,
      ocrScanning: true,
      staffAccounts: true,
      backups: true,
      restore: true,
      multiProperty: true,
      centralizedDashboard: true,
      rolePermissions: true,
      apiAccess: true,
      prioritySupport: true,
    },
  },
};
